default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5 %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: test_payment_dev

test:
  <<: *default
  database: test_payment_test

production:
  <<: *default
  database: test_payment_prod
  host: <%= ENV['POSTGRES_HOST'] %>
